name: FastPluginConfigurer
version: '${version}'
main: kz.hxncus.mc.fastpluginconfigurer.FastPluginConfigurer
softdepend:
  - DeluxeMenus
  - ChestCommands
commands:
  fastpluginconfigurer:
    aliases:
      - fpc
      - pluginconfigurer
