name: FastPluginConfigurer
version: '${version}'
main: kz.hxncus.mc.fastpluginconfigurer.FastPluginConfigurer
api-version: 1.13
softdepend:
  - DeluxeMenus
  - ChestCommands
  - zMenu
  - BetterGUI
commands:
  fastpluginconfigurer:
    aliases:
      - fpc
      - pluginconfigurer
